package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Cars;
import ba.unsa.etf.rpr.exceptions.CarsException;

import java.util.List;

public class CarsManager {

    public Cars add(Cars f) throws CarsException {
        if (f.getId() != 0) throw new CarsException("Cars can not already have an ID. ID is autogenerated.");
        try {
            return DaoFactory.carsDao().add(f);
        } catch (CarsException e) {
            throw new CarsException(e.getMessage(), e);
        }
    }

    public void delete(int filmId) throws CarsException {
        try {
            DaoFactory.carsDao().delete(filmId);
        } catch (CarsException e) {
            throw new CarsException(e.getMessage(), e);
        }
    }

    public Cars update(Cars cars) throws CarsException {
        return DaoFactory.carsDao().update(cars);
    }

    public List<Cars> getAll() throws CarsException {
        return DaoFactory.carsDao().getAll();
    }

    public List<Cars> getAllAvailable() throws CarsException{
        return DaoFactory.carsDao().getAllAvailable();
    }

    public Cars getById(int id) throws CarsException {
        return DaoFactory.carsDao().getById(id);
    }

  /*  public Integer getID(String marka, String model, Integer godiste, Integer cijena, boolean b) {

    }*/
}
